services:
  app:
    image: dblog-front
    container_name: dblog-front
    build:
      context: ./app/
      dockerfile: Dockerfile
    volumes:
      - ./app/:/usr/src/app
    environment:
      - VITE_BACKEND_URL=http://localhost:8080/api/

  server:
    image: dblog-back
    container_name: dblog-back
    build:
      context: ./api/
      dockerfile: Dockerfile
    volumes:
      - ./api/:/usr/src/app
    environment: 
      - MONGODB_URI=${MONGODB_URI}

  nginx:
    image: nginx:1.20.1
    container_name: dblog-reverse-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    depends_on:
      - app
      - server
